### ISSUE TITLE
Graphviz errors for abstract syntax tree (AST) vizualisation

### ISSUE THREAD

**Issue by ColdTeapot273K** [parrt/tensor-sensor#11]
* Issue:
Calls of tsensor.astviz() produce no vizualisation, but error: 

> FileNotFoundError: [WinError 2]

* Environment:
  * win10 latest (11.10.2020)
  * conda 4.8.5 virtual env
  * conda-installed graphviz 0.14.2 XOR pip-installed graphviz 0.14.2

* Notes:
  * Issue seems to be about _graphviz on windows in conda env_, as per [#1666](https://github.com/ContinuumIO/anaconda-issues/issues/1666).

* A working user-side fix (as per [#1666 comment](https://github.com/ContinuumIO/anaconda-issues/issues/1666#issuecomment-299490806), also tested by me) is:
  if using conda env, install graphviz only like `conda install python-graphviz`, instead of `pip install graphviz`

  So the proper installation process of the current release for conda users would be like:
`conda install python-graphviz`
`pip install tensor-sensor`

**Comment by parrt** [comment]
interesting! I use pip for my graphviz. at least I think. does this tell us it's in pip on my box?

```
beast:master:~/github/tensor-sensor $ conda list |grep graphviz
python-graphviz           0.14.1                   pypi_0    pypi
beast:master:~/github/tensor-sensor $ pip list |grep graphviz
graphviz                           0.14.1
```

**Comment by parrt** [comment]
OH! You need `brew install graphviz` also on mac, which graphviz py lib uses.  So maybe on windows we do `conda install python-graphviz`?
