### ISSUE TITLE
Seem a problem with np.ones() function

### ISSUE THREAD

**Issue by DemonsHunter** [parrt/tensor-sensor#16]
Hi! I really thank u for your brilliant work of tsensor which help me to debug more effectively.

But recently, when I run this code in Jupyter or Pycharm, it always leads to a KeyError:

**code:**
with ts.explain():
    a = np.ones(3)

**KeyError report:**
KeyError                                  Traceback (most recent call last)
<ipython-input-19-9b019b13ab66> in <module>()
      1 with ts.explain():
----> 2     a = np.ones(3)
      3 

F:\anaconda_file2\envs\test\lib\site-packages\numpy\core\numeric.py in ones(shape, dtype, order)
    206     """
    207     a = empty(shape, dtype, order)
--> 208     multiarray.copyto(a, 1, casting='unsafe')
    209     return a
    210 

<__array_function__ internals> in copyto(*args, **kwargs)

F:\anaconda_file2\envs\test\lib\site-packages\tsensor\analysis.py in listener(self, frame, event, arg)
    266 
    267     def listener(self, frame, event, arg):
--> 268         module = frame.f_globals['__name__']
    269         info = inspect.getframeinfo(frame)
    270         filename, line = info.filename, info.lineno

KeyError: '__name__'

Is there anything I can do to fix this problem? Grateful to gain any feedback!

**Comment by parrt** [comment]
Hi! Wow,  that is strange. Oh, are you using python2? that might be the issue.

On Python 3, I actually get a different error:

>>> with tsensor.explain():
...     a = np.ones(3)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 2, in <module>
  File "/Users/parrt/github/tensor-sensor/tsensor/analysis.py", line 274, in listener
    self.line_listener(module, name, filename, line, info, frame)
  File "/Users/parrt/github/tensor-sensor/tsensor/analysis.py", line 282, in line_listener
    code = info.code_context[0].strip()
TypeError: 'NoneType' object is not subscriptable

**Comment by DemonsHunter** [comment]
Sorry for applying too late, actually I use Python3. And I also wonder why the same code leads to different error.
I guess that it partly due to the tsenor does not include the function "np.ones".
I am not sure and I will keep an eye on related error or issues.

**Comment by parrt** [comment]
Ok, think I figured this out. You're using ipython and I'm using python. Also, it appears to be different if I run it in interactive mode!!! investigating
