### ISSUE TITLE
Supporting JAX

### ISSUE THREAD

**Issue by ethanluoyc** [parrt/tensor-sensor#17]
Hi, 

Thanks for the awesome library! This has really made my debugging life much easier.

Just a question. Is there any plan to support [JAX](https://jax.readthedocs.io/en/latest/)?   I think this can be similarly supported since the API of JAX almost looks identical to NumPy.

**Comment by parrt** [comment]
Heh, wow. jax looks really cool. I literally had not heard of this! Sure, I will poke around to see how this would work. parrt: check out [https://sjmielke.com/jax-purify.htm](https://sjmielke.com/jax-purify.htm)

**Comment by ethanluoyc** [comment]
Thanks for the interest! It's getting more attention these days and I have found it to be quite useful in a broader sense of ML (probabilistic modeling). Please let me know if there is anything that I can help with.

**Comment by parrt** [comment]
I'm just about done with this feature request. Would you care to try it out?

**Comment by ethanluoyc** [comment]
Wow this is absolutely amazing! I will give it a try and let you know how it works!

**Comment by parrt** [comment]
Lemme know what you think. it even works for weird stuff:

```
jnp.fft.fft(x, norm="something weird")
```

**Comment by ethanluoyc** [comment]
I just tried it out. It really works like magic. My work involves working with lots of broadcasting and reshaping so when something goes wrong it was usually very hard to understand what the problem is. Your work has really made things a lot simpler!

**Comment by parrt** [comment]
That's great to hear, @ethanluoyc !   It would be  very helpful if you could advertise TensorSensor in the JAX community :) thank you!

**Comment by ethanluoyc** [comment]
Definitely!
