### ISSUE TITLE
Not an issue - livepython fyi

### ISSUE THREAD

**Issue by johndpope** [parrt/tensor-sensor#37]
I know notebooks are most popular for ml - but consider there's some that prefer to drop in to command line and run python code.
In this case - there's this library that is quite amazing that could potentially be plugged in.
https://github.com/agermanidis/livepython

**Comment by parrt** [comment]
Yes I definitely use the command line with this library. Thanks for the pointer in case people are interested.

**Comment by johndpope** [comment]
It maybe 10 years from now - but I wish the pytorch team would take this livepython and 
add it to their roadmap where you could run the training or inference but have(maybe configure/plugin) a digestable  simplistic overview / latex - maths and sub disection of the of what's going on under the hood with some kind of ai explanatation of linear algebra. 
Or said another way - read the pdf papare - show the pytorch code - explain it / bridge the understanding 
- ask the user questions to see if they understand thing.
It's not necessarily - going to be a compiler - or even give / verify the correct results - but given this branch of ai (relevant papers / formulas that underpin it) - help to explain it for newbies. 

this code is running lines 50 - 100 - and it's working on this equation in the paper - based off the work of bengio et el (highlight picture of equation).
