### ISSUE TITLE
Contribution Guidelines 

### ISSUE THREAD

**Issue by skat00sh** [parrt/tensor-sensor#7]
I've a feeling that at some point many(including me) would like to contribute to this library and it would be great if it had some contribution guidelines.

**Comment by parrt** [comment]
Hi.  I just created an initial contributors.md.  Can you try to create (and don't commit) a new issue or pull request to see if the guidelines pop up?  I don't think it shows up for me as I'm  not a first-time contributor. Thanks!

**Comment by skat00sh** [comment]
this is what it looks like when I try to create a new issue
![Screenshot from 2020-10-12 12-07-19](https://user-images.githubusercontent.com/11071620/95734350-a4cbc980-0c83-11eb-82a5-c7a7b03e959b.png)
Seems about right to me :)

**Comment by parrt** [comment]
Excellent. hopefully that contributors document answer your questions. happy to add other stuff.
