### ISSUE TITLE
Remove hard torch dependecies for keras/tensorflow user

### ISSUE THREAD

**Issue by noklam** [parrt/tensor-sensor#9]
Currently, in the analysis.py `_shape` method it always try to check if `torch.Size` exist. So for a keras user, if they don't have torch install, it will throw an error since `analysis.py` is importing it.

```
  File "/home/shawley/Downloads/tensor-sensor/tsensor/analysis.py", line 27, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

Related #8

**Comment by drscotthawley** [comment]
Or even just for numpy users!  The first example in the documentation is only using numpy, not Keras/tensorflow.

**Comment by noklam** [comment]
I think this automatically works for NumPy too. Since only torch is imported explicitly

**Comment by parrt** [comment]
Fixed by https://github.com/parrt/tensor-sensor/pull/10

**Comment by parrt** [comment]
@drscotthawley please try now. thanks!

**Comment by drscotthawley** [comment]
@parrt  Works! Lovely!  Even outside of Jupyter.  When I run from the shell a little matplotlib-style window pops up showing the image.  Thanks!
